basePath: /api/v1/
definitions:
  github_com_iarsham_shop-api_internal_dto.RefreshTokenRequest:
    properties:
      refresh_token:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTY5NDE4MTcsInBob25lIjoiKzk4OTAyMTMxMjIyNCIsInVzZXJfaWQiOiI1In0.hzmZdfltaMDWaiTwO8IG1uPEyXOsu3JBs6giU2BDeMI
        type: string
    required:
    - refresh_token
    type: object
  github_com_iarsham_shop-api_internal_dto.RegisterLoginRequest:
    properties:
      first_name:
        example: James
        maxLength: 75
        minLength: 1
        type: string
      last_name:
        example: Rodriguez
        maxLength: 75
        minLength: 1
        type: string
      phone:
        example: "+989021112299"
        maxLength: 13
        minLength: 11
        type: string
    required:
    - phone
    type: object
  github_com_iarsham_shop-api_internal_dto.SendOTPRequest:
    properties:
      phone:
        example: "+989021112299"
        maxLength: 13
        minLength: 11
        type: string
    required:
    - phone
    type: object
  github_com_iarsham_shop-api_internal_dto.UpdateUserRequest:
    properties:
      first_name:
        example: James
        maxLength: 75
        minLength: 1
        type: string
      last_name:
        example: Rodriguez
        maxLength: 75
        minLength: 1
        type: string
    required:
    - first_name
    - last_name
    type: object
  github_com_iarsham_shop-api_internal_dto.VerifyOTPRequest:
    properties:
      code:
        example: "241960"
        maxLength: 6
        minLength: 6
        type: string
    required:
    - code
    type: object
  gorm.DeletedAt:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
  responses.InterServerErrorResponse:
    properties:
      response:
        example: Internal server error
        type: string
    type: object
  responses.LoginOKResponse:
    properties:
      response:
        example: Success, otp was sent
        type: string
    type: object
  responses.OtpExpiredResponse:
    properties:
      response:
        example: otp expired
        type: string
    type: object
  responses.OtpIncorrectResponse:
    properties:
      response:
        example: code is incorrect
        type: string
    type: object
  responses.RefreshTokenResponse:
    properties:
      response:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTY5NDE4MTcsInBob25lIjoiKzk4OTAyMTMxMjIyNCIsInVzZXJfaWQiOiI1In0.hzmZdfltaMDWaiTwO8IG1uPEyXOsu3JBs6giU2BDeMI
        type: string
    type: object
  responses.RegisterOKResponse:
    properties:
      response:
        example: Success, otp was sent
        type: string
    type: object
  responses.SendOtpOkResponse:
    properties:
      response:
        example: otp was sent
        type: string
    type: object
  responses.Token:
    properties:
      access-token:
        type: string
      refresh-token:
        type: string
    type: object
  responses.UserNotFoundResponse:
    properties:
      response:
        example: user not found
        type: string
    type: object
  responses.UserResponse:
    properties:
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      first_name:
        type: string
      id:
        type: integer
      is_active:
        type: boolean
      last_name:
        type: string
      phone:
        type: string
      updatedAt:
        type: string
    type: object
  responses.VerifyOTPResponse:
    properties:
      response:
        $ref: '#/definitions/responses.Token'
    type: object
host: localhost:8000
info:
  contact:
    email: arshamdev2001@gmail.com
  title: Shop API Document
paths:
  /otp/send:
    post:
      consumes:
      - application/json
      description: This endpoint receives the user's phone in request body and generates
        an otp. it then sends the otp to the user's phone via sms.
      parameters:
      - description: send otp body
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/github_com_iarsham_shop-api_internal_dto.SendOTPRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/responses.SendOtpOkResponse'
        "404":
          description: not found
          schema:
            $ref: '#/definitions/responses.UserNotFoundResponse'
      summary: Send OTP
      tags:
      - OTP
  /otp/verify:
    post:
      consumes:
      - application/json
      description: this endpoint receives the user's otp code in request body.if code
        match, the verification is successfully.
      parameters:
      - description: verify otp body
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/github_com_iarsham_shop-api_internal_dto.VerifyOTPRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/responses.VerifyOTPResponse'
        "401":
          description: incorrect
          schema:
            $ref: '#/definitions/responses.OtpIncorrectResponse'
        "410":
          description: Expired
          schema:
            $ref: '#/definitions/responses.OtpExpiredResponse'
      summary: Verify OTP
      tags:
      - OTP
  /token/refresh-token:
    post:
      consumes:
      - application/json
      description: Create new access token from refresh token
      parameters:
      - description: refresh token body
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/github_com_iarsham_shop-api_internal_dto.RefreshTokenRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/responses.RefreshTokenResponse'
        "500":
          description: Error
          schema:
            $ref: '#/definitions/responses.InterServerErrorResponse'
      summary: Get New AccessToken
      tags:
      - Tokens
  /user/:
    get:
      consumes:
      - application/json
      description: Retrieve user information by ID
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/responses.UserResponse'
        "500":
          description: Error
          schema:
            $ref: '#/definitions/responses.InterServerErrorResponse'
      summary: Get User
      tags:
      - Users
    put:
      consumes:
      - application/json
      description: Update user information by ID
      parameters:
      - description: update user body
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/github_com_iarsham_shop-api_internal_dto.UpdateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/responses.UserResponse'
        "500":
          description: Error
          schema:
            $ref: '#/definitions/responses.InterServerErrorResponse'
      summary: Update User
      tags:
      - Users
  /user/register-login:
    post:
      consumes:
      - application/json
      description: Create user with firstname / lastname / phone
      parameters:
      - description: register and login body
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/github_com_iarsham_shop-api_internal_dto.RegisterLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/responses.LoginOKResponse'
        "201":
          description: Success
          schema:
            $ref: '#/definitions/responses.RegisterOKResponse'
        "500":
          description: Error
          schema:
            $ref: '#/definitions/responses.InterServerErrorResponse'
      summary: Register And Login By Phone
      tags:
      - Users
schemes:
- http
- https
securityDefinitions:
  Authorization:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
