basePath: /api/v1/
definitions:
  dto.RegisterRequest:
    properties:
      first_name:
        example: James
        maxLength: 75
        minLength: 1
        type: string
      last_name:
        example: Rodriguez
        maxLength: 75
        minLength: 1
        type: string
      phone:
        example: "+989021112299"
        maxLength: 13
        minLength: 11
        type: string
    required:
    - first_name
    - last_name
    - phone
    type: object
  dto.SendOTPRequest:
    properties:
      phone:
        example: "+989021112299"
        maxLength: 13
        minLength: 11
        type: string
    required:
    - phone
    type: object
  dto.VerifyOTPRequest:
    properties:
      code:
        example: "241960"
        maxLength: 6
        minLength: 6
        type: string
      phone:
        example: "+989021112299"
        maxLength: 13
        minLength: 11
        type: string
    required:
    - code
    - phone
    type: object
  responses.InterServerErrorResponse:
    properties:
      response:
        example: Internal server error
        type: string
    type: object
  responses.OtpExpiredResponse:
    properties:
      response:
        example: otp expired
        type: string
    type: object
  responses.OtpIncorrectResponse:
    properties:
      response:
        example: code is incorrect
        type: string
    type: object
  responses.RegisterConflictResponse:
    properties:
      response:
        example: user with this phone already exists
        type: string
    type: object
  responses.RegisterOKResponse:
    properties:
      response:
        example: user created
        type: string
    type: object
  responses.SendOtpOkResponse:
    properties:
      response:
        example: otp was sent
        type: string
    type: object
  responses.UserNotFoundResponse:
    properties:
      response:
        example: user not found
        type: string
    type: object
  responses.VerifyOTPResponse:
    properties:
      access_token:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTYzMzg4MTcsInBob25lIjoiKzk4OTAyMTMxMjIyNCIsInVzZXJfaWQiOiI1In0.DAxOeyiWpPZWXyVnnyLajMQ9SGsBKw65qOAurhjlFy0
        type: string
      refresh_token:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTY5NDE4MTcsInBob25lIjoiKzk4OTAyMTMxMjIyNCIsInVzZXJfaWQiOiI1In0.hzmZdfltaMDWaiTwO8IG1uPEyXOsu3JBs6giU2BDeMI
        type: string
    type: object
host: localhost:8000
info:
  contact:
    email: arshamdev2001@gmail.com
  title: Shop API Document
paths:
  /user/register:
    post:
      consumes:
      - application/json
      description: Create user with firstname / lastname / phone
      parameters:
      - description: register body
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/dto.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Success
          schema:
            $ref: '#/definitions/responses.RegisterOKResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/responses.RegisterConflictResponse'
        "500":
          description: Error
          schema:
            $ref: '#/definitions/responses.InterServerErrorResponse'
      summary: Register By Phone
      tags:
      - Users
  /user/send-otp:
    post:
      consumes:
      - application/json
      description: This endpoint receives the user's phone in request body and generates
        an otp. it then sends the otp to the user's phone via sms.
      parameters:
      - description: send otp body
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/dto.SendOTPRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/responses.SendOtpOkResponse'
        "404":
          description: not found
          schema:
            $ref: '#/definitions/responses.UserNotFoundResponse'
      summary: Send OTP
      tags:
      - Users
  /user/verify-otp:
    post:
      consumes:
      - application/json
      description: this endpoint receives the user's phone and otp code in request
        body.if code match, the verification is successfully.
      parameters:
      - description: verify otp body
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/dto.VerifyOTPRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/responses.VerifyOTPResponse'
        "401":
          description: incorrect
          schema:
            $ref: '#/definitions/responses.OtpIncorrectResponse'
        "410":
          description: Expired
          schema:
            $ref: '#/definitions/responses.OtpExpiredResponse'
      summary: Verify OTP
      tags:
      - Users
schemes:
- http
- https
securityDefinitions:
  Authorization:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
